const data = {
    users: [
      {
        name: "Sakin",
        email: "sakinislam79@gmail.com",
        password: "123456454515",
        image: "",
        address: "123 Main Street, City, Country",
        phone: "156451446784",
      },
      {
        name: "mahid",
        email: "sakinislam790@gmail.com",
        password: "123256",
        image: "",
        address: "123 MainDhaka Street, City, Country",
        phone: "156451146784",
      },
      // Additional entries
      {
        name: "Alice Johnson",
        email: "alicejohnson@example.com",
        password: "alice1234",
        image: "",
        address: "789 Pine Street, Town, Country",
        phone: "1231231234",
      },
      {
        name: "Bob Smith",
        email: "bobsmith@example.com",
        password: "bob456",
        image: "",
        address: "456 Maple Avenue, Village, Country",
        phone: "4564564567",
      },
      {
        name: "Emily Brown",
        email: "emilybrown@example.com",
        password: "password123",
        image: "",
        address: "321 Oak Street, Suburb, Country",
        phone: "7897897890",
      },
      {
        name: "Michael Davis",
        email: "michaeldavis@example.com",
        password: "michael789",
        image: "",
        address: "654 Elm Avenue, City, Country",
        phone: "0980980987",
      },
      {
        name: "Sophia Wilson",
        email: "sophiawilson@example.com",
        password: "sophia456",
        image: "",
        address: "987 Cedar Road, Town, Country",
        phone: "3453453456",
      },
      {
        name: "Daniel Martinez",
        email: "danielmartinez@example.com",
        password: "daniel123",
        image: "",
        address: "852 Birch Lane, Village, Country",
        phone: "6546546543",
      },
      {
        name: "Olivia Taylor",
        email: "oliviataylor@example.com",
        password: "olivia789",
        image: "",
        address: "159 Pine Street, City, Country",
        phone: "3213213210",
      },
      {
        name: "Liam Anderson",
        email: "liamanderson@example.com",
        password: "liam456",
        image: "",
        address: "753 Elm Avenue, Suburb, Country",
        phone: "9879879876",
      },
      {
        name: "Ava Garcia",
        email: "avagarcia@example.com",
        password: "ava123",
        image: "",
        address: "369 Oak Street, Town, Country",
        phone: "7417417410",
      },
      {
        name: "Noah Hernandez",
        email: "noahhernandez@example.com",
        password: "noah789",
        image: "",
        address: "258 Cedar Lane, City, Country",
        phone: "9639639630",
      },
      {
        name: "Emma Lopez",
        email: "emmalopez@example.com",
        password: "emma456",
        image: "",
        address: "147 Maple Avenue, Village, Country",
        phone: "8528528521",
      },
      {
        name: "William Martinez",
        email: "williammartinez@example.com",
        password: "william123",
        image: "",
        address: "852 Pine Street, Suburb, Country",
        phone: "3693693690",
      },
      {
        name: "Isabella Lee",
        email: "isabellalee@example.com",
        password: "isabella789",
        image: "",
        address: "753 Cedar Road, Town, Country",
        phone: "7418529630",
      },
      {
        name: "James Robinson",
        email: "jamesrobinson@example.com",
        password: "james456",
        image: "",
        address: "963 Elm Lane, City, Country",
        phone: "1593572580",
      },
      {
        name: "Charlotte Perez",
        email: "charlotteperez@example.com",
        password: "charlotte123",
        image: "",
        address: "369 Maple Street, Village, Country",
        phone: "8527419630",
      },
      {
        name: "Benjamin Gonzalez",
        email: "benjamingonzalez@example.com",
        password: "benjamin789",
        image: "",
        address: "147 Cedar Avenue, Suburb, Country",
        phone: "3698521470",
      },
      {
        name: "Amelia Walker",
        email: "ameliawalker@example.com",
        password: "amelia456",
        image: "",
        address: "258 Pine Lane, Town, Country",
        phone: "7419638520",
      },
      {
        name: "Alexander Hall",
        email: "alexanderhall@example.com",
        password: "alexander123",
        image: "",
        address: "753 Oak Road, City, Country",
        phone: "1598527410",
      },
      {
        name: "Mia Young",
        email: "miayoung@example.com",
        password: "mia789",
        image: "",
        address: "963 Cedar Street, Village, Country",
        phone: "8529637410",
      },
      {
        name: "Ethan Flores",
        email: "ethanflores@example.com",
        password: "ethan456",
        image: "",
        address: "369 Elm Avenue, Suburb, Country",
        phone: "7412589630",
      },
      {
        name: "Harper Scott",
        email: "harperscott@example.com",
        password: "harper123",
        image: "",
        address: "147 Maple Lane, Town, Country",
        phone: "9637418520",
      },
      {
        name: "Abigail Green",
        email: "abigailgreen@example.com",
        password: "abigail789",
        image: "",
        address: "258 Oak Street, City, Country",
        phone: "8523697410",
      },
      {
        name: "Michael White",
        email: "michaelwhite@example.com",
        password: "michael456",
        image: "",
        address: "753 Pine Road, Village, Country",
        phone: "3697418520",
      },
      {
        name: "Ella Adams",
        email: "ellaadams@example.com",
        password: "ella123",
        image: "",
        address: "963 Cedar Lane, Suburb, Country",
        phone: "7418523690",
      },
      {
        name: "Daniel Baker",
        email: "danielbaker@example.com",
        password: "daniel789",
        image: "",
        address: "147 Elm Street, Town, Country",
        phone: "9632587410",
      },
      {
        name: "Scarlett Nelson",
        email: "scarlettnelson@example.com",
        password: "scarlett456",
        image: "",
        address: "258 Maple Avenue, City, Country",
        phone: "7413698520",
      },
      {
        name: "Matthew Carter",
        email: "matthewcarter@example.com",
        password: "matthew123",
        image: "",
        address: "753 Cedar Street, Village, Country",
        phone: "3698521470",
      },
      {
        name: "Madison King",
        email: "madisonking@example.com",
        password: "madison789",
        image: "",
        address: "369 Pine Lane, Suburb, Country",
        phone: "8529637410",
      },
      {
        name: "Henry Hayes",
        email: "henryhayes@example.com",
        password: "henry456",
        image: "",
        address: "147 Oak Road, Town, Country",
        phone: "9637418520",
      },
    ],
  };
  
  export { data };